import puppeteer from "puppeteer";

interface FactFindData {
  userName: string;
  answers: Array<{
    question: string;
    answer: string;
  }>;
  signatureData?: string;
  date: string;
}

/**
 * Generate PDF from fact find data
 */
export async function generateFactFindPDF(data: FactFindData): Promise<Buffer> {
  // Launch headless browser
  const browser = await puppeteer.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  });

  try {
    const page = await browser.newPage();
    
    // Generate HTML content for PDF
    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>Insurance Fact Find - ${data.userName}</title>
        <style>
          body {
            font-family: Arial, sans-serif;
            margin: 20px;
            color: #333;
          }
          .header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 10px;
            border-bottom: 1px solid #ddd;
          }
          .logo {
            font-size: 24px;
            font-weight: bold;
            color: #2563eb;
          }
          h1 {
            font-size: 22px;
            margin: 10px 0;
          }
          .date {
            font-size: 14px;
            color: #666;
            margin-bottom: 20px;
          }
          .section {
            margin-bottom: 20px;
          }
          .question {
            font-weight: bold;
            margin-bottom: 5px;
          }
          .answer {
            margin-left: 20px;
            margin-bottom: 15px;
          }
          .signature-container {
            margin-top: 40px;
            border-top: 1px solid #ddd;
            padding-top: 20px;
          }
          .signature {
            max-width: 300px;
            margin-bottom: 10px;
          }
          .signature-label {
            font-style: italic;
            color: #666;
          }
          .footer {
            margin-top: 40px;
            font-size: 12px;
            color: #666;
            text-align: center;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="logo">InsureAI</div>
          <h1>Insurance Fact Find Summary</h1>
          <div class="date">Generated on: ${data.date}</div>
        </div>
        
        <div class="section">
          <h2>Client Information</h2>
          <p>Name: ${data.userName}</p>
        </div>
        
        <div class="section">
          <h2>Fact Find Responses</h2>
          ${data.answers.map(item => `
            <div class="question">${item.question}</div>
            <div class="answer">${item.answer}</div>
          `).join('')}
        </div>
        
        <div class="signature-container">
          <h2>Client Confirmation</h2>
          <p>
            I confirm that the information provided in this document is accurate and complete to the best of my knowledge.
          </p>
          ${data.signatureData ? `
            <img class="signature" src="${data.signatureData}" alt="Client Signature" />
          ` : ''}
          <div class="signature-label">Client Signature: ${data.userName}</div>
        </div>
        
        <div class="footer">
          This document was generated by InsureAI on ${data.date}. 
          All information provided is subject to verification.
        </div>
      </body>
      </html>
    `;

    await page.setContent(html, { waitUntil: 'networkidle0' });
    
    // Generate PDF
    const pdfBuffer = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: {
        top: '20px',
        right: '20px',
        bottom: '20px',
        left: '20px'
      }
    });

    return pdfBuffer;
  } finally {
    await browser.close();
  }
}

export default {
  generateFactFindPDF,
};
